# Generated by Django 6.0.2 on 2026-02-26 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_covered', models.BooleanField(default=False)),
                ('is_ev_charging', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['slot_no'],
            },
        ),
    ]
